import Foundation

/// Original learning examples inspired by reusable speaking skills, not scripts to memorise.
enum SpeakingStarterPack {
    static let materials: [SpeakingMaterial] = {
        typealias K = SpeakingMaterial.Kind
        typealias P = SpeakingMaterial.Part
        let rows: [(String, String, String, String, String, String, K, P)] = [
            ("Friends matter", "Friends are important to me because we can share ideas and help each other with coursework.", "朋友对我很重要：我们交流想法，也互相帮助完成课程作业。", "Do you think friends are important?", "先直接回答，再补一个原因和你自己的具体例子。泛指用 friends are；share ideas。", "Friends", .sentence, .one),
            ("A recent friendship", "I met a few new classmates when I started my fourth year. One of my courses involved teamwork, and we have been working together since then.", "大四开始时认识了新同学，一门课需要团队合作，之后一直一起做作业。", "Have you made any new friends recently?", "got/started/involved 讲过去事件；have been working 连接到现在。替换成真实经历，不必为了回答而虚构朋友。", "Friends", .story, .one),
            ("A truthful no", "Not recently, to be honest. I've been busy preparing for an exam, so I haven't had many chances to meet new people.", "最近没有。我忙着备考，没有太多认识新人的机会。", "Have you made any new friends recently?", "否定答案也能展开：No → 原因 → 一个细节。不要为了使用习语把日常句子变得很重。", "Friends", .sentence, .one),
            ("Talking to strangers", "I'm a little shy around people I don't know, but I usually relax once we find something in common.", "面对陌生人有点害羞，找到共同话题后会放松。", "Do you enjoy talking to new people?", "people I don't know 比 familiar people 更贴合这个意思；also: people I'm not familiar with。", "Friends", .sentence, .one),
            ("Strengthen the bonds", "Sharing a meal gives people time to talk and strengthen their bonds.", "一起吃饭让人有机会聊天、增进感情。", "Why do people enjoy eating together?", "strengthen the bonds between friends/family members。先说明发生了什么，再补人际关系角度，避免只报社会学术语。", "Relationships", .phrase, .three),
            ("Busy with", "I've been swamped with coursework lately, so I haven't had much free time.", "最近课程作业很多，没什么空闲时间。", "What have you been doing recently?", "be swamped with = 忙得不可开交。用于确实很忙的情况；busy with 更中性。", "Studies", .phrase, .one),
            ("Make practical use of learning", "The tutorial showed me how to organise a simple workflow, and I put what I learned into practice the next day.", "教程教我组织简单的工作流程，第二天就把所学用于实践。", "Describe an online video that taught you something new.", "put what I learned into practice；learn how to... / acquire knowledge。缺词时优先用短句解释。", "Learning", .phrase, .two),
            ("A video that taught me something", "One video that comes to mind is a tutorial about making a short video with AI tools. I found it one evening while scrolling through recommendations. It broke the process into three steps: choosing a topic, finding useful information and turning it into a draft. I was trying to make my first video, so I tried those steps on a small project. The result wasn't perfect, but I finally understood where to start. What mattered most was being able to put the advice into practice.", "一个 AI 视频教程：偶然看到、三个步骤、自己的小项目、具体收获。", "Describe an online video that taught you something new.", "提纲：what → when/where → 内容两点 → why → 具体改变。只记五个关键词，换成自己的工具和结果。可迁移到学技能、实用网站、完成项目等题。", "Learning", .story, .two),
            ("Opening without a fixed template", "One example that comes to mind is a short tutorial I watched last week.", "首先想到的是上周看的一个短教程。", "Introduce a video, book or experience you learned from.", "开场要快速进入具体对象。也可以直接说 I'd like to talk about...，句子简单不等于扣分。", "Storytelling", .sentence, .two),
            ("Add one scene detail", "It was a quiet evening, and I was sitting on the sofa scrolling through videos when the tutorial caught my attention.", "一个安静的晚上，我在沙发上刷视频，那个教程吸引了我。", "Where were you when you discovered it?", "时间、地点、动作选一个有用细节即可，别让布景挤占真正的经历和收获。", "Storytelling", .sentence, .two),
            ("An eye-opener", "It was an eye-opener for me because I realised I could automate some tasks I'd always done by hand.", "它让我大开眼界：原来一些手工任务可以自动化。", "Why was the experience useful?", "说清新的认识。I'd always done = 在发现之前一直做的事，不必强行每题用过去完成时。", "Learning", .phrase, .two),
            ("Interested in a subject", "I'm intrigued by how these tools work, but I still need to learn the basics.", "我对这些工具如何工作感兴趣，但还要学习基础知识。", "Why did you choose to learn this skill?", "be interested in / fascinated by / intrigued by；不要写 be appealed by，通常用 it appeals to me。", "Learning", .correction, .two),
            ("Condense a film", "These videos condense a two-hour film into a ten-minute summary, which makes them easy to watch on a short break.", "这些视频把两小时电影浓缩成十分钟梗概，休息时方便看。", "What kinds of videos are popular?", "condense A into B；想不起 condense 时说 give a short summary of the film。保住表达再升级措辞。", "Media", .phrase, .three),
            ("Addicted to", "I sometimes get addicted to scrolling through short videos and lose track of time.", "我有时沉迷刷短视频，忘了时间。", "Do you spend too much time on social media?", "get addicted to + 名词或动名词，不用 into；lose track of time = 忘了时间。", "Media", .correction, .one),
            ("Small pockets of time", "Short videos fit into small pockets of free time, such as a bus journey or a break between classes.", "短视频适合坐公交、课间休息这类零碎空闲时间。", "Why do people watch short videos?", "small pockets of free time 比 consume fragmented time 更自然。例子把抽象说法落地。", "Media", .phrase, .three),
            ("Unwind", "After a long day, watching a few light-hearted videos helps me unwind.", "忙了一天，看几个轻松视频让我放松。", "Why do you watch videos?", "unwind / recharge my batteries，先掌握一个能随口用的表达即可。", "Media", .phrase, .one),
            ("People and platforms", "People often watch short videos to relax after work. At the same time, platforms recommend more of what they already enjoy, which can make it hard to stop watching.", "人们想放松，平台又不断推荐喜欢的内容，于是不容易停下来。", "Why do people spend so much time watching short videos?", "两条因果：人的需求 + 平台机制。谈机制即可，不需要声称刷视频必然降低皮质醇。", "Media", .angle, .three),
            ("Classify an abstract question", "It depends on the audience. Younger viewers may enjoy comedy or gaming clips, while some older viewers prefer news or practical advice.", "要看受众：年轻观众可能喜欢搞笑、游戏，一些年长观众喜欢新闻、实用建议。", "What kinds of videos are popular in your country?", "分类 → 具体类型 → 原因。may/some 避免把年龄群体说成绝对一致，也可以按兴趣或使用场景分类。", "Media", .angle, .three),
            ("Compare online and in-person learning", "Online lessons are convenient because people can learn at their own pace. That being said, face-to-face classes make it easier to ask questions and practise with others.", "线上学习方便、自定节奏；线下更容易提问、与别人练习。", "Will online learning replace face-to-face learning?", "观点 → 原因 → 对比 → 限定。that being said 用来转折，不要每句堆一个连接词。", "Learning", .angle, .three),
            ("Explain a missing word", "I can't think of the exact word, but I mean a video that gives you the main points of a whole film in a few minutes.", "想不起精确词，但能解释：几分钟讲清整部电影要点的视频。", "Explain a film-summary video without using condense.", "练释义替代：what it does + an example。练习时刻意禁用关键词，让表达不中断。", "Paraphrase", .sentence, .any),
            ("Restaurant experience", "People don't always go out just for the food. They may enjoy the atmosphere and the chance to spend time with friends, so the experience matters as much as the meal.", "去餐厅不只是吃饭，也享受氛围和朋友相处的时间。", "Why do people like eating in restaurants?", "先给容易懂的因果和例子，再视需要提 experience economy。概念名称不是单独的得分点。", "Food", .angle, .three),
            ("Online information: benefit and limit", "The internet gives us quick access to information, but not everything we read is reliable. For example, a convincing post may still contain misinformation.", "网络让信息获取便捷，但有些可信的帖子也可能包含错误信息。", "What are the disadvantages of getting information online?", "便利 + 可靠性边界。misinformation 是错误信息；不一定是蓄意的 disinformation。", "Technology", .angle, .three),
            ("A sense of belonging", "I've lived here for most of my life, so I have a strong sense of belonging. Even the small local shops feel familiar to me.", "在这里住了很久，有很强的归属感，连小店也很熟悉。", "How long have you lived in your area?", "have lived / have been living；时间 → 感受 → 细节。born and raised in... 可用，但别强行套固定家乡描述。", "Home", .phrase, .one),
            ("Find something engaging", "I found the video engaging because the presenter used clear examples instead of complicated explanations.", "视频很吸引我，讲者用清楚的例子而非复杂解释。", "What made the video interesting?", "find + 宾语 + 形容词；I think the video is interesting 也正确，并非母语者绝不会用。", "Learning", .correction, .two),
            ("General nouns and pronouns", "Friends can help each other. I feel comfortable talking to them, even when I don't know what to say.", "朋友会互相帮助。就算不知道说什么，跟他们聊天也安心。", "Explain why friends matter using friends and them.", "一轮只练一个自动化点：friends are / people are；talk to him or her / talk to them。先用三个新场景反复说，再混合练。", "Grammar", .correction, .any),
            ("Transfer a story", "The most useful part was trying the advice myself. At first I made several mistakes, but after changing one step I got a result I was happy with.", "先试建议、犯错、调整一个步骤，最终有满意的结果。", "Adapt a learning experience to a skill, a useful video or a successful project.", "同一真实故事换焦点：视频题讲视频内容；技能题讲怎么练；成就题讲困难和结果。不要不看题卡套同一全文。", "Storytelling", .story, .two)
        ]
        return rows.enumerated().map { index, row in
            var item = SpeakingMaterial(title: row.0, english: row.1, chinese: row.2, prompt: row.3,
                notes: row.4, topic: row.5, kind: row.6, part: row.7, source: "Starter pack · adapted example")
            item.id = UUID(uuidString: String(format: "73504541-4B49-4000-8000-%012d", index + 1))!
            item.createdAt = Date(timeIntervalSince1970: 0)
            return item
        }
    }()
}
