import AppKit
import Foundation

/// A lexical gate, not a general clipboard reader. Never persists clipboard contents.
enum ClipboardWord {
    static func parse(_ value: String) -> String? {
        guard value.utf8.count <= 128, !value.contains("\n"), !value.contains("\r") else { return nil }
        let word = value.trimmingCharacters(in: .whitespaces)
        guard (1...32).contains(word.count) else { return nil }
        let pattern = #"^[A-Za-z]+(?:[-'’][A-Za-z]+)*$"#
        guard word.range(of: pattern, options: .regularExpression) != nil else { return nil }
        let letters = word.filter { $0.isLetter }
        // Mixed case strings frequently represent identifiers, rather than selected vocabulary.
        guard letters == letters.lowercased() || letters == letters.uppercased()
            || letters == letters.prefix(1).uppercased() + letters.dropFirst().lowercased() else { return nil }
        guard letters.count > 1 || ["a", "i"].contains(letters.lowercased()) else { return nil }
        return word
    }
}

struct ClipboardChangeGate {
    private(set) var lastChangeCount: Int?
    mutating func reset(changeCount: Int) { lastChangeCount = changeCount }
    mutating func consume(changeCount: Int, value: () -> String?) -> String? {
        guard lastChangeCount != changeCount else { return nil }
        lastChangeCount = changeCount
        return value().flatMap(ClipboardWord.parse)
    }
}

@MainActor
final class ClipboardWordMonitor {
    var onCandidate: ((String?) -> Void)?
    private let pasteboard: NSPasteboard
    private var gate = ClipboardChangeGate()
    private var timer: Timer?
    private var observers: [NSObjectProtocol] = []
    private(set) var enabled = false
    private var awake = true

    init(pasteboard: NSPasteboard = .general) { self.pasteboard = pasteboard }

    func setEnabled(_ enabled: Bool) {
        guard self.enabled != enabled else { return }
        self.enabled = enabled
        timer?.invalidate(); timer = nil
        if enabled {
            // Existing clipboard contents are not inspected when switching the setting on.
            gate.reset(changeCount: pasteboard.changeCount)
            if observers.isEmpty {
                let center = NSWorkspace.shared.notificationCenter
                observers.append(center.addObserver(forName: NSWorkspace.willSleepNotification, object: nil,
                    queue: .main) { [weak self] _ in MainActor.assumeIsolated { self?.awake = false } })
                observers.append(center.addObserver(forName: NSWorkspace.didWakeNotification, object: nil,
                    queue: .main) { [weak self] _ in MainActor.assumeIsolated { self?.awake = true } })
            }
            let timer = Timer(timeInterval: 1.0, repeats: true) { [weak self] _ in
                MainActor.assumeIsolated { self?.poll() }
            }
            RunLoop.main.add(timer, forMode: .common)
            self.timer = timer
        } else { onCandidate?(nil) }
    }

    private func poll() {
        guard enabled, awake, gate.lastChangeCount != pasteboard.changeCount else { return }
        // Skip password-manager / transient clipboard markers without reading their value.
        let privateTypes = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"]
        let privateContent = privateTypes.contains { pasteboard.types?.contains(NSPasteboard.PasteboardType($0)) == true }
        let candidate = gate.consume(changeCount: pasteboard.changeCount) {
            privateContent ? nil : pasteboard.string(forType: .string)
        }
        onCandidate?(candidate)
    }

    deinit {
        timer?.invalidate()
        for observer in observers { NSWorkspace.shared.notificationCenter.removeObserver(observer) }
    }
}
